#!/bin/bash -eu

# Pass the path to an initSh script, and this will remove any orphaned instance
# directories, previous existing cache, and all temporary files. Only call when
# you guarantee that no one is concurrently invoking initSh on the project.

runScript=$1   

binDir=$(dirname $(readlink -f $0))
. $binDir/lib.sh

nukeRuntime
